### ISSUE TITLE
Use "clothing" instead of "3d_armor"

### ISSUE THREAD

**Issue by bell07** [GreenXenith/halloween#2]
I think the costume should be clothing, not armor: https://github.com/stujones11/clothing

Because the clothing requires multiskin or skinsdb to run, and because of this dependency some user does not like to install them, the 3d_armor code should not be removed. Maybe condition like
"if cloting mod found, then clothing code, else 3d_armor code"...

**Comment by GreenXenith** [comment]
I am sort of against this.
For one, I do not see any way to register a full "suit" using the clothing mod.
Second, sure I can support both, but that would require either some heavy texture modifiers, or a new clothing-format texture for each costume, both of which I really don't want to do.
I do not see a real need either, considering 3d_armor is a commonly used mod, and serves it's function rather well.
